### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by donxbei** [tianyong90/we-vue#27]
## 我用的环境

OS:win10
浏览器：chrome
webpack 版本：最新
we-vue 版本：最新

如何改变Textarea里 背景颜色呢

**Comment by tianyong90** [comment]
虽然组件本身并不提供属性来设置背景色，但这可以通过自写样式来实现。如果像下面这样。

```css
<style>
  .weui-textarea {
    background-color: red;
  }
</style>
```

还可以这样，先给 textarea 添加 id 或 class 属性后再定义样式
```vue
<template>
  <wv-textarea id="mytext" />
</template>

<style>
  #mytext .weui-textarea {
    background: #ccc;
  }
</style>
